name: Continous integration
on:
  push:
    branches:
      - '!master'
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    name: Cypress
    strategy:
      matrix:
        browser: [chrome]
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v1
        env:
          REACT_APP_ANALYTICS_API_KEY: ${{ secrets.REACT_APP_ANALYTICS_API_KEY }}
          REACT_APP_GIPHY_API_KEY: ${{ secrets.REACT_APP_GIPHY_API_KEY }}
          SKIP_PREFLIGHT_CHECK: true
        with:
          browser: ${{ matrix.browser }}
          start: npm start
          wait-on: 'http://localhost:3000'
          env: ci=true
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
